# Generated by Django 2.2.5 on 2019-10-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ikntprofils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(db_index=True)),
                ('name', models.TextField(db_index=True)),
                ('val', models.TextField(db_index=True)),
            ],
        ),
    ]
