# Generated by Django 2.2.5 on 2019-11-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20191112_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='ikntprofils',
            name='val',
            field=models.TextField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
