# Generated by Django 2.2.5 on 2019-11-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_ikntprofils_val'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mc3025',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
                ('val', models.TextField(db_index=True)),
            ],
        ),
    ]
