# Generated by Django 2.2.5 on 2019-12-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20191205_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='A305',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('val', models.TextField()),
            ],
        ),
    ]
