# Generated by Django 2.2.5 on 2019-12-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_a305'),
    ]

    operations = [
        migrations.CreateModel(
            name='A402',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('val', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='A405',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('val', models.TextField()),
            ],
        ),
    ]
